title: Thoughts about Microscopes
author: nico
description: just testing
#theme: minima 
remote_theme: "jekyll/minima@767779bc98dde488ac535a7cf690119c304c77d4"
#remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
